name: learn-github-actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: true
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - run: npm install -g bats
      - run: bats -v
      
      - name: NPM-Version
        uses: Reedyuk/NPM-Version@1.1.1
        with:
          version: '0.3.1'
          package: ./
          
      - name: Current Version Checkout
        run: npm run version
